on:
  push:
    branches:
      - main
    paths:
      - update.mjs
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm run update
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore: update"
          file_pattern: README.md
